url: https://snowdj.github.io/great-waterfall

author: snowdj
email: snowdj@gmail.com

disqus_shortname: jonduan
github_repo: snowdj/great-waterfall

google_analytics:

markdown: kramdown
permalink: /:year/:month/:title/
highlighter: rouge
