url: https://snowdj.github.io/uvicecon
author: snowdj
email: snowdj@gmail.com

disqus_shortname: jonduan
github_repo: snowdj/uvicecon

google_analytics:

markdown: kramdown
permalink: /:year/:month/:title/
highlighter: rouge
