url: https://snowdj.github.io/great-waterfall

author: 谢益辉
email: xie@yihui.name

disqus_shortname: jonduan
github_repo: snowdj/great-waterfall

google_analytics:

markdown: kramdown
permalink: /:year/:month/:title/
highlighter: rouge
